springdoc:
  api-docs:
    path: /docs

management:
  endpoint:
    shutdown:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/stdn
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  server:
    port: 8082

